/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutosSlugRouteImport } from './routes/produtos.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosSlugRoute = ProdutosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProdutosRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/faq': typeof FaqRoute
  '/privacidade': typeof PrivacidadeRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/faq': typeof FaqRoute
  '/privacidade': typeof PrivacidadeRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/faq': typeof FaqRoute
  '/privacidade': typeof PrivacidadeRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/contacto'
    | '/faq'
    | '/privacidade'
    | '/produtos'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/blog/$slug'
    | '/produtos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/contacto'
    | '/faq'
    | '/privacidade'
    | '/produtos'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/blog/$slug'
    | '/produtos/$slug'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/contacto'
    | '/faq'
    | '/privacidade'
    | '/produtos'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/blog/$slug'
    | '/produtos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  FaqRoute: typeof FaqRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProdutosRoute: typeof ProdutosRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/$slug': {
      id: '/produtos/$slug'
      path: '/$slug'
      fullPath: '/produtos/$slug'
      preLoaderRoute: typeof ProdutosSlugRouteImport
      parentRoute: typeof ProdutosRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ProdutosRouteChildren {
  ProdutosSlugRoute: typeof ProdutosSlugRoute
}

const ProdutosRouteChildren: ProdutosRouteChildren = {
  ProdutosSlugRoute: ProdutosSlugRoute,
}

const ProdutosRouteWithChildren = ProdutosRoute._addFileChildren(
  ProdutosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactoRoute: ContactoRoute,
  FaqRoute: FaqRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ProdutosRoute: ProdutosRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
